"""empty message

Revision ID: 0fd22b1cc5d4
Revises: 7382980fe9a3
Create Date: 2024-04-25 15:21:44.778221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fd22b1cc5d4'
down_revision = '7382980fe9a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crawler', schema=None) as batch_op:
        batch_op.add_column(sa.Column('crawler_type', sa.String(length=128), nullable=True))
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crawler', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=128), nullable=True))
        batch_op.drop_column('crawler_type')

    # ### end Alembic commands ###
