"""empty message

Revision ID: 7382980fe9a3
Revises: 9899eff799d2
Create Date: 2024-04-18 11:04:33.559776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7382980fe9a3'
down_revision = '9899eff799d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_owner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner', sa.String(length=128), nullable=True))
        batch_op.drop_index('ix_content_owner_name')
        batch_op.create_index(batch_op.f('ix_content_owner_owner'), ['owner'], unique=False)
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_owner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=128), nullable=True))
        batch_op.drop_index(batch_op.f('ix_content_owner_owner'))
        batch_op.create_index('ix_content_owner_name', ['name'], unique=False)
        batch_op.drop_column('owner')

    # ### end Alembic commands ###
