"""empty message

Revision ID: 80aadd61aa77
Revises: 
Create Date: 2024-04-05 12:05:05.678410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80aadd61aa77'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('target',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('uri', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('target', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_target_description'), ['description'], unique=False)
        batch_op.create_index(batch_op.f('ix_target_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_target_uri'), ['uri'], unique=False)

    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('result', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['target_id'], ['target.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_result'), ['result'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_result'))

    op.drop_table('job')
    with op.batch_alter_table('target', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_target_uri'))
        batch_op.drop_index(batch_op.f('ix_target_title'))
        batch_op.drop_index(batch_op.f('ix_target_description'))

    op.drop_table('target')
    # ### end Alembic commands ###
