"""empty message

Revision ID: 9899eff799d2
Revises: 3ceec5f3406f
Create Date: 2024-04-17 14:15:59.299173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9899eff799d2'
down_revision = '3ceec5f3406f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_id', sa.String(length=100), nullable=True))
        batch_op.drop_column('resultOutcome')
        batch_op.drop_column('storagepath')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('storagepath', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('resultOutcome', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('task_id')

    # ### end Alembic commands ###
