"""empty message

Revision ID: 9e1516211b00
Revises: 
Create Date: 2024-04-15 14:47:46.920757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e1516211b00'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('type', sa.String(length=128), nullable=True),
    sa.Column('cmd', sa.String(length=128), nullable=True),
    sa.Column('settings', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crawler', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crawler_cmd'), ['cmd'], unique=False)
        batch_op.create_index(batch_op.f('ix_crawler_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_crawler_settings'), ['settings'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('target',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('target', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_target_description'), ['description'], unique=False)
        batch_op.create_index(batch_op.f('ix_target_title'), ['title'], unique=False)

    op.create_table('content_owner',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('reference_code', sa.String(length=128), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['target_id'], ['target.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_owner', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_owner_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_owner_reference_code'), ['reference_code'], unique=False)

    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('storagepath', sa.String(length=100), nullable=True),
    sa.Column('resultOutcome', sa.String(length=100), nullable=True),
    sa.Column('stats', sa.String(length=100), nullable=True),
    sa.Column('QA', sa.String(length=100), nullable=True),
    sa.Column('schedule', sa.String(length=100), nullable=True),
    sa.Column('startDateTime', sa.DateTime(), nullable=True),
    sa.Column('EndDateTime', sa.DateTime(), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('crawler_id', sa.Integer(), nullable=True),
    sa.Column('result', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['crawler_id'], ['crawler.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['target.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=128), nullable=True),
    sa.Column('depth', sa.Integer(), nullable=True),
    sa.Column('exclude_patterns', sa.String(length=128), nullable=True),
    sa.Column('include_patterns', sa.String(length=128), nullable=True),
    sa.Column('domains', sa.String(length=128), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['target_id'], ['target.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('seed', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seed_depth'), ['depth'], unique=False)
        batch_op.create_index(batch_op.f('ix_seed_domains'), ['domains'], unique=False)
        batch_op.create_index(batch_op.f('ix_seed_exclude_patterns'), ['exclude_patterns'], unique=False)
        batch_op.create_index(batch_op.f('ix_seed_include_patterns'), ['include_patterns'], unique=False)
        batch_op.create_index(batch_op.f('ix_seed_url'), ['url'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seed', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seed_url'))
        batch_op.drop_index(batch_op.f('ix_seed_include_patterns'))
        batch_op.drop_index(batch_op.f('ix_seed_exclude_patterns'))
        batch_op.drop_index(batch_op.f('ix_seed_domains'))
        batch_op.drop_index(batch_op.f('ix_seed_depth'))

    op.drop_table('seed')
    op.drop_table('job')
    with op.batch_alter_table('content_owner', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_owner_reference_code'))
        batch_op.drop_index(batch_op.f('ix_content_owner_name'))

    op.drop_table('content_owner')
    with op.batch_alter_table('target', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_target_title'))
        batch_op.drop_index(batch_op.f('ix_target_description'))

    op.drop_table('target')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    with op.batch_alter_table('crawler', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crawler_settings'))
        batch_op.drop_index(batch_op.f('ix_crawler_name'))
        batch_op.drop_index(batch_op.f('ix_crawler_cmd'))

    op.drop_table('crawler')
    # ### end Alembic commands ###
